# sample configuration file

# data loading
PHONEME_TXT_FILEPATH: "data/phonemes.txt"

TRAIN_DATA_DIR: "data/train-clean-100" 
DEV_DATA_DIR: "data/dev-clean" 


# configurables
context_len: 200
device_num_workers: 4

model:
  first_layer_activation: "softplus"
  linear:
    - 1024
    - 1024
    - 512
  activation:
    - "softplus"
    - "softplus"
    - "relu"
  dropout:
    - 0.05
    - 0.08
    - 0.10
  batchnorm:
    - true
    - true
    - true
  init: "kaiming"

optimizer:
  name: AdamW
  configs:
    lr: 1.2e-3

training:
  epochs: 3
  batch_size: 8196
  eval_per_epoch: 3

inference:
  batch_size: 8196
