# sample configuration file

# data loading
PHONEME_TXT_FILEPATH: "data/phonemes.txt"

TRAIN_DATA_DIR: "data/train-clean-100" 
DEV_DATA_DIR: "data/dev-clean" 


# configurables
context_len: 7

model:
  first_layer_activation: "relu"
  linear:
    - 1024
    - 512
    - 512
  activation:
    - "relu"
    - "relu"
    - "relu"
  dropout:
    - 0.1
    - 0.1
    - 0.1
  batchnorm:
    - false
    - false
    - true
  init: "xavier"

optimizer:
  name: Adam
  configs:
    lr: 1.0e-3

training:
  epochs: 2
  batch_size: 8192
  eval_per_epoch: 3

inference:
  batch_size: 8192
