# sample configuration file

# data loading parameters -- stay unchanged for one fixed mission
PHONEME_TXT_FILEPATH: "data/phonemes.txt"
TRAIN_DATA_DIR: "data/train-clean-100" 
DEV_DATA_DIR: "data/dev-clean" 


# configurables
context_len: 50
device_num_workers: 8

model:
  add_squares: true
  first_layer_activation: "softplus"
  linear:
    - 2048
    - 2048
    - 1024
    - 1024
  activation:
    - "softplus"
    - "softplus"
    - "softplus"
    - "softplus"
  dropout:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
  batchnorm:
    - true
    - true
    - true
    - true
  init: "kaiming"

optimizer:
  name: AdamW
  configs:
    lr: 1.0e-4

training:
  seed: 11785
  epochs: 10
  batch_size: 10000
  eval_per_epoch: 5
  init_checkpoint: "'[**your-checkpoint-here**]"
  load_optimizer_checkpoint: false

inference:
  batch_size: 10000
