# sample configuration file

# data loading
PHONEME_TXT_FILEPATH: "data/phonemes.txt"

TRAIN_DATA_DIR: "data/train-clean-100" 
DEV_DATA_DIR: "data/dev-clean" 


# configurables
context_len: 10

model:
  first_layer_activation: "relu"
  linear:
    - 512
    - 1024
    - 512
    - 256
  activation:
    - "relu"
    - "relu"
    - "relu"
    - "relu"
  dropout:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
  batchnorm:
    - true
    - true
    - false
    - false
  init: "xavier"

optimizer:
  name: Adam
  configs:
    lr: 1.0e-3

training:
  epochs: 3
  batch_size: 2048
  eval_per_epoch: 3

inference:
  batch_size: 2048
